export const INCANTESIMI_TASHA = [
  { nome: 'Lama Rombante', livello: 0, scuola: 'Invocazione', tempo: '1 azione', gittata: 'Mischia', componenti: 'S, M', durata: '1 round', desc: 'Effettui attacco mischia, bersaglio avvolto da magia. Se si muove volontariamente subisce 1d8 danni tuono (scala con livelli).', classi: ['Mago', 'Stregone', 'Warlock', 'Artefice'] },
  { nome: 'Lama di Fiamma Verde', livello: 0, scuola: 'Invocazione', tempo: '1 azione', gittata: 'Mischia', componenti: 'S, M', durata: 'Istantanea', desc: 'Effettui attacco mischia. Fiamme avvolgono arma infliggendo danni aggiuntivi al bersaglio e a un nemico adiacente.', classi: ['Mago', 'Stregone', 'Warlock', 'Artefice'] },
  { nome: 'Dardo Mentale', livello: 0, scuola: 'Ammaliamento', tempo: '1 azione', gittata: '18m', componenti: 'V', durata: 'Istantanea', desc: 'Danni psichici 1d6, prossimo tiro salvezza del nemico riceve malus di 1d4.', classi: ['Bardo', 'Stregone', 'Mago', 'Warlock'] },
  { nome: 'Onda del Terrore', livello: 1, scuola: 'Necromanzia', tempo: '1 azione', gittata: 'Cubo 4.5m', componenti: 'V', durata: 'Istantanea', desc: 'Nemici in area TS Sag o spaventati.', classi: ['Warlock', 'Mago'] },
  { nome: 'Armatura Magica Psionica', livello: 1, scuola: 'Abiurazione', tempo: '1 bonus', gittata: 'Personale', componenti: 'V, S', durata: '1 ora', desc: 'CA aumenta e resistenze magiche.', classi: ['Artefice', 'Mago'] },
  { nome: 'Nube Venefica', livello: 2, scuola: 'Evocazione', tempo: '1 azione', gittata: 'Sfera 6m', componenti: 'V, S', durata: 'Concentrazione (1 min)', desc: 'Danni veleno ricorrenti nell\'area oscurata e svantaggio.', classi: ['Druido', 'Stregone'] },
  { nome: 'Sfera Mentale Psionica', livello: 3, scuola: 'Invocazione', tempo: '1 azione', gittata: '27m', componenti: 'V', durata: 'Istantanea', desc: 'Sfera che fa danni psichici e riduce velocità.', classi: ['Stregone', 'Mago', 'Bardo'] },
  { nome: 'Manto Spirituale', livello: 3, scuola: 'Necromanzia', tempo: '1 azione bonus', gittata: 'Personale', componenti: 'V, S', durata: 'Concentrazione', desc: 'I tuoi attacchi fanno 1d8 danni radianti/necrotici/freddo bonus e limiti mov.', classi: ['Chierico', 'Paladino'] },
  { nome: 'Passo del Fey', livello: 4, scuola: 'Evocazione', tempo: '1 azione bonus', gittata: 'Personale', componenti: 'V', durata: '1 round', desc: 'Teletrasporti di 9m e accechi nemici.', classi: ['Ranger', 'Warlock'] },
  { nome: 'Evoca Bestia', livello: 2, scuola: 'Evocazione', tempo: '1 azione', gittata: '27m', componenti: 'V, S, M', durata: 'Concentrazione', desc: 'Evoca bestia terreste, mare, volo (scala in base allo slot).', classi: ['Druido', 'Ranger'] },
  { nome: 'Evoca Celestiale', livello: 5, scuola: 'Evocazione', tempo: '1 azione', gittata: '27m', componenti: 'V, S, M', durata: 'Concentrazione', desc: 'Evoca Vendicatore o Difensore divino (stat base fisse Tasha).', classi: ['Chierico', 'Paladino'] },
  { nome: 'Evoca Aberrazione', livello: 4, scuola: 'Evocazione', tempo: '1 azione', gittata: '27m', componenti: 'V, S, M', durata: 'Concentrazione', desc: 'Evoca mostro Slaad o beholderoid.', classi: ['Warlock', 'Mago', 'Stregone'] },
  { nome: 'Lama del Disastro', livello: 9, scuola: 'Evocazione', tempo: '1 azione bonus', gittata: '18m', componenti: 'V, S', durata: 'Concentrazione', desc: 'Spada dimensionale, infligge ferite spaventose e ignora protezioni magiche.', classi: ['Mago', 'Stregone', 'Warlock'] }
];
